# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ff52c3368827143459b2af8c50fde2513683d22cc2eada1af66f023c3ac025f13cd60cf674e405f72b6184432e7fba13b6ed6bb553db1a96e8118bd161a1815

test:
  secret_key_base: 2779e378e08ce9a03960e199dc88bd2a75907085b0480e5439755cbface4a6215f110d25e0cfccf4f937cfe9f24e87eab4c6d74b515b16b2be4731157ef010c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
